from gempaa import * 

gempa1 = Gempa('Banten', 1.2)
gempa2 = Gempa('Palu', 6.1)
gempa3 = Gempa('Cianjur', 5.4)
gempa4 = Gempa('Jayapura', 3.3)
gempa5 = Gempa('Garut', 4.0)


print('====Gempa Bumi Info====')
print()
gempa1.dampak(1.2)
print()
print('====Gempa Bumi Info====')
print()
gempa2.dampak(6.1)
print()
print('====Gempa Bumi Info====')
print()
gempa3.dampak(5.4)
print()
print('====Gempa Bumi Info====')
print()
gempa4.dampak(3.3)
print()
print('====Gempa Bumi Info====')
print()
gempa5.dampak(4.0)
print()
